datasets:
    name: 'wireframe'
    input_size: 512

model:
    model_name: 'mobilev2_mlsd_large'
    with_deconv: True


train:
    # save_dir:  './workdir/models/mobilev2_mlsd_large_512_base2_bsize24_LSDdataset_only_link'
    save_dir:  './workdir/models/test'
    img_dir:  "./data/LSD_dataset/images/"
    label_fn: "./data/LSD_dataset/train_only_link.json"
    num_train_epochs: 50
    batch_size: 13
    learning_rate: 0.001
    use_step_lr_policy: True
    weight_decay: 0.001
    load_from: "workdir/pretrained_models/mobilev2_mlsd_large_512_bsize24/best.pth"
    # load_from: "workdir/models/mobilev2_mlsd_large_512_base2_bsize24_LSDdataset_only_link/best.pth"
    warmup_steps: 50
    milestones: [ 20, 30, 40]
    milestones_in_epo: True
    lr_decay_gamma: 0.1

    data_cache_dir: "./data/LSD_dataset_cache/"
    with_cache: False
    cache_to_mem: False

val:
    img_dir: "./data/LSD_dataset/images/"
    label_fn: "./data/LSD_dataset/val_only_link.json"
    batch_size: 13
    val_after_epoch: 1

loss:
    loss_weight_dict_list: [ { 'tp_center_loss': 10.0,'sol_center_loss': 1.0,'tp_match_loss': 1.0 } ]
    with_match_loss: False
    with_focal_loss: True
    focal_loss_level: 0
    with_sol_loss: True
    match_sap_thresh: 5.0

decode:
    score_thresh: 0.05
    len_thresh: 10
    top_k: 500